{
 "title": "Consul",
 "description": "Get performance metrics from Consul metrics prometheus endpoint /agent/metrics?format=prometheus. Tested with Consul 1.4.4, Prometheus 2.10.0 and Grafana 6.2.4. Although can potentially work with other versions.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consul",
    "query": "label_values(consul_memberlist_gossip_sum, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consul Leader",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "consul_raft_state_leader", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "UP",
   "type": "graph",
   "description": "Is it running at all?",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"$consul\"}"
    }
   ]
  },
  {
   "title": "# servers in cluster",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "COUNT (changes(consul_memberlist_gossip_sum[1m]) > 0) BY (labels)"
    }
   ]
  },
  {
   "title": "consul_autopilot_healthy",
   "type": "graph",
   "description": "Tracks the overall health of the local server cluster. If all servers are considered healthy by autopilot, this will be set to 1. If any are unhealthy, this will be 0.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_autopilot_healthy" }
   ]
  },
  {
   "title": "consul.raft.state.leader",
   "type": "graph",
   "description": "This increments whenever a Consul server becomes a leader.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_raft_state_leader" }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$consul\"}[5m]) / 12 * 100"
    }
   ]
  },
  {
   "title": "consul.raft.state.candidate",
   "type": "graph",
   "description": "consul.raft.state.candidate = this increments whenever a Consul server starts an election.  candidate == 0. Deviations from 0 might indicate flapping leadership.\n\nconsul.serf.member.join\tThis increments when an agent joins the cluster. If an agent flapped or failed this counter also increments when it re-joins.\t\n\nconsul.serf.member.left\tThis increments when an agent leaves the cluster.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_raft_state_candidate" },
    {
     "expr": "consul_serf_member_join{instance=\"$consul\"}"
    },
    {
     "expr": "consul_serf_member_left{instance=\"$consul\"}"
    },
    {
     "expr": "consul_serf_member_update{instance=\"$consul\"}"
    }
   ]
  },
  {
   "title": "consul_runtime_gc_pause",
   "type": "graph",
   "description": "GC pause is a \"stop-the-world\" event, meaning that all runtime threads are blocked until GC completes. Normally these pauses last only a few nanoseconds. But if memory usage is high, the Go runtime may GC so frequently that it starts to slow down Consul.\nWarning if total_gc_pause_ns exceeds 2 seconds/minute, critical if it exceeds 5 seconds/minute.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(consul_runtime_gc_pause_ns{instance=\"$consul\"}[1m])/1000000",
     "legendFormat": "{{quantile}}%"
    },
    {
     "expr": "sum_over_time(consul_runtime_gc_pause_ns{instance=\"$consul\"}[1m])/1000000",
     "legendFormat": "sum/1m {{quantile}}%"
    }
   ]
  },
  {
   "title": "Raft Transactions",
   "type": "graph",
   "description": "This counts the number of Raft transactions occurring over the interval, which is a general indicator of the write load on the Consul servers.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "delta(consul_raft_apply[30s])", "legendFormat": "Transactions" }
   ]
  },
  {
   "title": "consul_runtime_alloc_bytes",
   "type": "graph",
   "description": "This measures the number of bytes allocated by the Consul process. Consul keeps all of its data in memory. If Consul consumes all available memory, it will crash.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "consul_runtime_alloc_bytes/1048576 "
    }
   ]
  },
  {
   "title": "Commit time Leader",
   "type": "graph",
   "description": "This measures the time it takes to commit a new entry to the Raft log on the leader. Generally these should all be fairly consistent and no more than a few milliseconds. Sudden changes in any of the timing values could be due to unexpected load on the Consul servers, or due to problems on the servers themselves.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_commitTime{instance=\"$consul\"}",
     "legendFormat": "raft_commitTime {{quantile}}%"
    },
    {
     "expr": "irate(consul_serf_snapshot_appendLine{instance=\"$consul\"}[1m])",
     "legendFormat": "snapshot_appendLine {{quantile}}%"
    }
   ]
  },
  {
   "title": "Memberlist TCP Messages",
   "type": "graph",
   "description": "The amount of TCP messages that are sent/received from the server.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(consul_memberlist_tcp_connect{instance=\"$consul\"}[1m])",
     "legendFormat": "connect"
    },
    {
     "expr": "irate(consul_memberlist_tcp_sent{instance=\"$consul\"}[1m])",
     "legendFormat": "sent"
    },
    {
     "expr": "irate(consul_memberlist_tcp_accept{instance=\"$consul\"}[1m])",
     "legendFormat": "accept"
    }
   ]
  },
  {
   "title": "Memberlist UDP Messages",
   "type": "graph",
   "description": "The amount of UDP messages in bytes that are sent/received from the server.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(consul_memberlist_udp_sent{instance=\"$consul\"}[1m])",
     "legendFormat": "sent"
    },
    {
     "expr": "irate(consul_memberlist_udp_received{instance=\"$consul\"}[1m])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Write logs",
   "type": "graph",
   "description": "This measures the time it takes for the leader to write log entries to disk.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_leader_dispatchLog", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "consul_raft_replication_heartbeat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_replication_heartbeat",
     "legendFormat": "{{query}} - {{quantile}}%"
    }
   ]
  },
  {
   "title": "Log replication from leader to servers",
   "type": "graph",
   "description": "This measures the time it takes to replicate log entries to followers. This is a general indicator of the load pressure on the Consul servers, as well as the performance of the communication between the servers.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_replication_appendEntries_rpc",
     "legendFormat": "{{query}} - {{quantile}}%"
    }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(consul_rpc_query{host=\"$consul\"}[30s])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Serf Coordinates",
   "type": "graph",
   "description": "Consul uses a network tomography system to compute network coordinates for nodes in the cluster. These coordinates allow the network round trip time to be estimated between any two nodes using a very simple calculation. This allows for many useful applications, such as finding the service node nearest a requesting node, or failing over to services in the next closest datacenter.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_serf_coordinate_adjustment_ms{host=\"$consul\"}",
     "legendFormat": "{{quantile}}%"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$consul\"}"
    },
    {
     "expr": "process_open_fds{instance=\"$consul\"}"
    }
   ]
  },
  {
   "title": "consul_catalog_service_not_found",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_catalog_service_not_found{instance=\"$consul\"}"
    }
   ]
  },
  {
   "title": "Consul Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{instance=\"$consul\"}"
    },
    {
     "expr": "consul_runtime_num_goroutines{instance=\"$consul\"}"
    }
   ]
  }
 ]
}