FROM grafana/grafana
USER root
RUN apt-get update && \
    apt-get -y --no-install-recommends install curl

RUN mkdir -p /var/lib/grafana/dashboards
COPY ./grafana/grafana.json /usr/share/grafana/public/dashboards/home.json

COPY ./grafana/bootstrap.sh /
ENTRYPOINT ["/bootstrap.sh"]
