{
 "title": "linkerd-viz",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "router", "query": "label_values(rt)" },
   { "name": "service", "query": "label_values(client)" },
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div>\n  <div style=\"position: absolute; bottom: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/logo-100h.png\" style=\"height: 40px;\"></a>\n  </div>\n  <div style=\"position: absolute; bottom: 0; right: 0; font-size: 15px\">\n    linkerd enables\n    <a href=\"https://linkerd.io/in-depth/concepts/#service-discovery\" target=\"_blank\">service discovery</a>,\n    <a href=\"https://linkerd.io/in-depth/routing/\" target=\"_blank\">routing</a>, and\n    <a href=\"https://linkerd.io/in-depth/routing/#load-balancing\" target=\"_blank\">load balancing</a>.\n    <a href=\"https://linkerd.io/getting-started/\" target=\"_blank\">Learn more &raquo;</a>\n    <br>\n    Need help? Join us on <a href=\"http://slack.linkerd.io\" target=\"_blank\">the linkerd Slack</a>.\n  </div>\n</div>\n"
  },
  {
   "title": "Services Monitored",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(rt:client:requests{rt=\"$router\"}) by (client))"
    }
   ]
  },
  {
   "title": "linkerd Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(jvm:uptime) by(instance))"
    }
   ]
  },
  {
   "title": "Global Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(rt:client:success{rt=\"$router\"}[1m])) / sum(irate(rt:client:requests{rt=\"$router\"}[1m]))"
    }
   ]
  },
  {
   "title": "Global Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(rt:client:requests{rt=\"$router\"}[1m]))"
    }
   ]
  },
  {
   "title": "4XX Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(rt:client:status:4XX{rt=\"$router\"}[1m]))"
    }
   ]
  },
  {
   "title": "5XX Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(rt:client:status:5XX{rt=\"$router\"}[1m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>TOP LINE</span>\n</div>\n"
  },
  {
   "title": "Success Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(rt:client:success{rt=\"$router\",client=~\"$service\",instance=~\"$instance\"}[1m])) by (client) / sum(irate(rt:client:requests{rt=\"$router\", client=~\"$service\",instance=~\"$instance\"}[1m])) by (client), .0001)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Request Volumes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rt:client:requests{rt=\"$router\",client=~\"$service\",instance=~\"$instance\"}[1m])) by (client)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rt:client:request_latency_ms{rt=\"$router\",quantile=\"0.95\",client=~\"$service\",instance=~\"$instance\"}) by (client)",
     "legendFormat": "p95_{{client}}"
    },
    {
     "expr": "max(rt:client:request_latency_ms{rt=\"$router\",quantile=\"0.99\",client=~\"$service\",instance=~\"$instance\"}) by (client)",
     "legendFormat": "p99_{{client}}"
    },
    {
     "expr": "max(rt:client:request_latency_ms{rt=\"$router\",quantile=\"1\",client=~\"$service\",instance=~\"$instance\"}) by (client)",
     "legendFormat": "max_{{client}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>SERVICE METRICS</span>\n</div>\n"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "service" },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "content": "<div>\n  <img src=\"https://linkerd.io/images/logo-only-200h.png\" style=\"baseline; height:40px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">$service</span>\n</div>\n"
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "round(irate(rt:client:success{rt=\"$router\",client=~\"$service\",instance=~\"$instance\"}[1m]) / irate(rt:client:requests{rt=\"$router\",client=~\"$service\",instance=~\"$instance\"}[1m]), .0001)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(rt:client:requests{rt=\"$router\",client=~\"$service\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rt:client:request_latency_ms{rt=\"$router\",quantile=\"0.95\",client=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "max(rt:client:request_latency_ms{rt=\"$router\",quantile=\"0.99\",client=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "max(rt:client:request_latency_ms{rt=\"$router\",quantile=\"1\",client=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>PER-INSTANCE METRICS</span>\n</div>\n"
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(rt:server:success{rt=\"$router\",instance=~\"$instance\"}[1m])) by (instance) / sum(irate(rt:server:requests{rt=\"$router\",instance=~\"$instance\"}[1m])) by (instance), .0001)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rt:server:requests{rt=\"$router\",instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rt:server:request_latency_ms{rt=\"$router\",quantile=\"0.95\",instance=~\"$instance\"}",
     "legendFormat": "p95_{{instance}}"
    },
    {
     "expr": "rt:server:request_latency_ms{rt=\"$router\",quantile=\"0.99\",instance=~\"$instance\"}",
     "legendFormat": "p99_{{instance}}"
    },
    {
     "expr": "rt:server:request_latency_ms{rt=\"$router\",quantile=\"1\",instance=~\"$instance\"}",
     "legendFormat": "max_{{instance}}"
    }
   ]
  }
 ]
}